Models/CreateViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Hitchhikers.Models
{
    public class CreateViewModel
    {
        [Required]
        [Display(Name = "Photo")]
        public string PictName {get; set;}

        [Required]
        [Display(Name = "States")]
        public string States {get; set;}
        
        [Required]
        [Display(Name = "City")]
        public string City {get; set;}

        [Required]
        [Display(Name = "Description")]
        public string Description {get; set;}

        [Display(Name= "Address(optional)")]
        public string Address { get; set; }

        [Required(ErrorMessage = "Date of Visit is required")]
        [Display(Name = "Date of Visit")]
        public DateTime DateOfVisit {get; set;}
    }
}

Controllers/TravelController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Hitchhikers.Models;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Hosting;
using System.Web;
using System.Drawing;
using System.Net.Http.Headers;
using System.IO;
using Microsoft.AspNetCore.Hosting.Internal;

namespace Hitchhikers.Controllers
{
    public class TravelController : Controller
    {
        private TravelContext _dbcontext;
        private Random rnd = new Random(Guid.NewGuid().GetHashCode());
        private readonly IHostingEnvironment hostingEnvironment;

        //Constructor
        public TravelController(TravelContext context, IHostingEnvironment environment)
        {
            _dbcontext = context;
            hostingEnvironment = environment;

        }

        [HttpGet]
        [Route("/Dashboard")]
        public IActionResult Dashboard()
        {
            if (!CheckLoggedIn())
            {
                return RedirectToAction("SignIn", "Home");
            }
            ViewBag.CurrentUserID = (int)HttpContext.Session.GetInt32("CurrentUserID");
            int UserID = ViewBag.CurrentUserID;
            var User = _dbcontext.Users.Where(u => u.Userid == (int)HttpContext.Session.GetInt32("CurrentUserID"))
                                    .Include(pic => pic.Uploaded).ToList();
            var alluploaded = _dbcontext.Pictures.Where(user => user.UploaderId == UserID).ToList();
            User userState = _dbcontext.Users.Where(u => u.Userid == (int)HttpContext.Session.GetInt32("CurrentUserID"))
                                    .Include(pic => pic.Uploaded).SingleOrDefault();
            var states = _dbcontext.Pictures.Where(v => v.UploaderId == (int)HttpContext.Session.GetInt32("CurrentUserID")).ToList();

            JsonSerializerSettings jss = new JsonSerializerSettings();
            jss.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;

            ViewBag.MostVisted = MostVisted(userState).Take(5); ;
            ViewBag.MyStates = JsonConvert.SerializeObject(states, jss);
            ViewBag.AllUploaded = alluploaded;
            ViewBag.Count = alluploaded.Count;
            ViewBag.User = User;
            return View("Dashboard");
        }

        [HttpGet]
        [Route("/Create")]
        public IActionResult Create(string Page)
        {
            if (!CheckLoggedIn())
            {
                return RedirectToAction("SignIn", "Home");
            }
            HttpContext.Session.SetString("PageName", Page);
            ViewBag.CurrentUserID = (int)HttpContext.Session.GetInt32("CurrentUserID");
            List<string> StateList = new List<string>
            { "AL", "AK", "AS", "AZ", "AR", "CA", "CO", "CT", "DE", "DC","FM", "FL","GA", "GU","HI","ID","IL", "IN", "IA","KS","KY","LA","ME", "MH", "MD", "MA", "MI","MN","MS","MO", "MT", "NE","NV","NH","NJ", "NM", "NY", "NC", "ND","MP","OH","OK", "OR",  "PW", "PA","PR","RI", "SC", "SD", "TN","TX","UT","VT", "VI", "VA", "WA", "WV", "WI","WY"};
            ViewBag.all_states = StateList;
            return View("Create");
        }

        [HttpPost]
        [Route("/AddPhoto")]
        public IActionResult AddPhoto(CreateViewModel model, List<IFormFile> PictName)
        {
            System.Console.WriteLine(model.States);
            // if(ModelState.IsValid) 
            // {
            long size = PictName.Sum(f => f.Length);
            string strfullPath = "";
            // full path to file in temp location
            var filePath = Path.GetTempFileName();

            foreach (var formFile in PictName)
            {
                var uploads = Path.Combine(hostingEnvironment.WebRootPath, "images");
                var fullPath = Path.Combine(uploads, GetUniqueFileName(formFile.FileName));
                strfullPath = GetUniqueFileName(formFile.FileName);
                formFile.CopyTo(new FileStream(fullPath, FileMode.Create));
            }

            Picture NewPicture = new Picture
            {
                UploaderId = (int)HttpContext.Session.GetInt32("CurrentUserID"),
                States = model.States,
                City = model.City,
                PictName = strfullPath,
                DateVisited = model.DateOfVisit,
                Description = model.Description,
                Address = model.Address
            };

            _dbcontext.Pictures.Add(NewPicture);
            _dbcontext.SaveChanges();
            string PageName = (string)HttpContext.Session.GetString("PageName");

            if (PageName != "Dashboard")
            {
                return RedirectToAction("CollectivePhotos", new { state = model.States });
            }
            return RedirectToAction("Dashboard");
        }
        private string GetUniqueFileName(string fileName)
        {
            fileName = Path.GetFileName(fileName);
            return fileName;
        }

        [HttpGet]
        [Route("/CollectivePhotos/viewPicture/{picID}")]
        public IActionResult ViewPicture(int picID)
        {
            ViewBag.CurrentUserID = (int)HttpContext.Session.GetInt32("CurrentUserID");
            if (!CheckLoggedIn())
            {
                return RedirectToAction("SignIn", "Home");
            }
            Picture photo = _dbcontext.Pictures.Where(e => e.PictureId == picID).Include(p => p.Uploader).SingleOrDefault();
            ViewBag.Pic = photo;

            var comment = _dbcontext.Comments.Include(u => u.Sender).Where(c => c.PictureId == picID).Include(u => u.Sender).ToList();
            ViewBag.Comment = comment;
            return View("ViewPicture");
        }


        [HttpGet]
        [Route("/CollectivePhotos/viewUser/{userID}")]
        [Route("/CollectivePhotos/viewUser/viewUser/{userID}")]
        public IActionResult ViewUser(int UserID)
        {
            if (!CheckLoggedIn())
            {
                return RedirectToAction("SignIn", "Home");
            }
            var User = _dbcontext.Users.Where(u => u.Userid == UserID)
                                    .Include(pic => pic.Uploaded).ToList();
            ViewBag.CurrentUserID = (int)HttpContext.Session.GetInt32("CurrentUserID");

            User userState = _dbcontext.Users.Where(u => u.Userid == (int)HttpContext.Session.GetInt32("CurrentUserID"))
                                    .Include(pic => pic.Uploaded).SingleOrDefault();
            ViewBag.MostVisted = MostVisted(userState).Take(5);

            var uploaded = _dbcontext.Pictures.Where(user => user.UploaderId == UserID).GroupBy(s => s.States).ToList();
            var alluploaded = _dbcontext.Pictures.Where(user => user.UploaderId == UserID).ToList();
            int count = _dbcontext.Pictures.Where(user => user.UploaderId == UserID).Count();
            var states = _dbcontext.Pictures.Where(v => v.UploaderId == UserID).ToList();

            JsonSerializerSettings jss = new JsonSerializerSettings();
            jss.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
            ViewBag.AllUploaded = alluploaded;
            ViewBag.Count = count;
            ViewBag.User = User;
            ViewBag.MyStates = JsonConvert.SerializeObject(states, jss);

            return View("Dashboard");
        }

        [HttpPost]
        [Route("/comment")]
        public IActionResult Comment(int photoID, string comment)
        {
            Comment newComment = new Comment
            {
                CommentText = comment,
                SenderId = (int)HttpContext.Session.GetInt32("CurrentUserID"),
                PictureId = photoID
            };
            _dbcontext.Comments.Add(newComment);
            _dbcontext.SaveChanges();
            // return RedirectToAction("ViewPicture", new { photoID = photoID });
            return Redirect($"/CollectivePhotos/viewPicture/{photoID}");
        }

        // route needs to be configure 
        [HttpGet]
        [Route("/CollectivePhotos/viewPicture/delete/{Cmtid}")]
        public IActionResult DeleteCmt(int Cmtid)
        {
            int CurrentUserID = (int)HttpContext.Session.GetInt32("CurrentUserID");
            Comment deleteCmt = _dbcontext.Comments.Where(e => e.Commentid == Cmtid).SingleOrDefault();
            if (deleteCmt.SenderId != CurrentUserID)
            {
                return Redirect($"/CollectivePhotos/ViewPicture/{deleteCmt.PictureId}");
            }
            _dbcontext.Comments.Remove(deleteCmt);
            _dbcontext.SaveChanges();
            return Redirect($"/CollectivePhotos/ViewPicture/{deleteCmt.PictureId}");
        }


        [HttpGet]
        [Route("/CollectivePhotos/{state}")]
        public IActionResult CollectivePhotos(string state)
        {
            if (!CheckLoggedIn())
            {
                return RedirectToAction("SignIn", "Home");
            }
            ViewBag.CurrentUserID = (int)HttpContext.Session.GetInt32("CurrentUserID");
            var Pictures = _dbcontext.Pictures.Include(users => users.Uploader).Where(states => states.States == state).ToList();
            ViewBag.DisplayPhoto = Pictures;
            ViewBag.state = state;
            return View("CollectivePhotos");
        }
    
        [HttpGet]
        [Route("/StartChat")]
        public IActionResult StartChat()
        {
            if (!CheckLoggedIn())
            {
                return RedirectToAction("Login", "Home");
            }
            ViewBag.CurrentUserID = (int)HttpContext.Session.GetInt32("CurrentUserID");
            User user = _dbcontext.Users.Where(e => e.Userid == (int)HttpContext.Session.GetInt32("CurrentUserID")).SingleOrDefault();
            ViewBag.CurrentUser = user.FirstName;
            ViewBag.UserColor = Getcolor();
            return View("Chatroom");
        }

        public IActionResult Error()
        {

Views/Travel/Chatroom.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="assets/css/bootstrap-responsive.css" rel="stylesheet">
    <title>@ViewData["Title"] Hitchhikers</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link href="https://fonts.googleapis.com/css?family=Lobster+Two:400,700|Yeseva+One" rel="stylesheet">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">

    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
            asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
            asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body id="ChatroomBg">
    <nav class="navbar navbar-inverse navbar-fixed-top navbar-custom">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Hitchhikers</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Travel" asp-action="Dashboard">Dashboard</a></li>
                    <li><a asp-area="" asp-controller="Travel" asp-action="StartChat">Chat Room</a></li>
                    @{
                        if(@ViewBag.CurrentUserID == null){
                            <li><a asp-area="" asp-controller="Home" asp-action="SignIn">Login</a></li>
                        }else{
                            <li><a asp-area="" asp-controller="Home" asp-action="Logout">Logout</a></li>
                        }
                    }
                </ul>
            </div>
        </div>
    </nav>
    

<div class="container">
    <div class="row">
        <div class="col-md-6 col-12 chatroom">
            <div class="row">
                <div class="col-md-12 text-center">
                    <i class="fas fa-plane"></i>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 chatbox">
                    <ul id="messagesList"></ul>
                </div>
            </div>
        <div class="row">
            <form>
                <input type="hidden" id="userInput" value=@ViewBag.CurrentUser />
                <input type="hidden" id="fontcolor" value=@ViewBag.UserColor />
                <br />
                <div class="col-md-10"> 
                    <input type="text" id="messageInput" class="messageInput form-control" placeholder="Enter Message"/>
                </div>
                <div class="col-md-2">
                    <input type="submit" id="sendButton" value="Send" class="btn btn-primary sendBtn form-control"/>
                </div>
            </form>
        </div>
        </div>
    <div class="col-md-6 col-12 col12none"></div>
    </div>
    
    
    <script src="~/lib/signalr.js"></script>
    <script src="~/js/chat.js"></script>
    @*<script src="~/js/es5-chat.js"></script>*@

    </body>
</html>

Views/Travel/CollectivePhotos.cshtml
@model Hitchhikers.Models.Picture

 <div class="container">
    <div class="col text-center">
      <h1>Welcome to @ViewBag.state</h1>
    </div>
    <div class="col"></div>
    <div class="col"></div>
    <div class="row mt-5">
      @{ 
          
        foreach (var pictures in @ViewBag.DisplayPhoto)
        {
          <div class="col-sm-12 col-md-3">
            <div class="thumbnail">
              <a href="viewPicture/@pictures.PictureId"><img src="~/images/@pictures.PictName" alt="image_pic" class="photosize"></a>
              <div class="caption">
                <div class="row">
                  <div class="col-md-12">
                    <p>@pictures.City, @pictures.States</p> 
                    <p>@pictures.Address</p>
                  </div>
                </div>
                <div class="row text-right">
                  <div class="col-md-12">
                    <p>-by <a href="viewUser/@pictures.Uploader.Userid">@pictures.Uploader.FirstName @pictures.Uploader.LastName</a></p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        }
      }
    </div>
    <div class="row">
      <div class="col-md-12 text-right">
          <form asp-controller="Travel" asp-action="Create" method="get">
              <button type="submit" class="btn btn-primary">Add new picture</button>
              <input type="hidden" value="CollectivePhotos" name="Page">
          </form>
      </div>
    </div>
</div>

Views/Travel/Create.cshtml
@model Hitchhikers.Models.CreateViewModel
<div class="row mt30">
    <div class="col-md-6">
        <h2>Picture Upload</h2>
        <form asp-controller="Travel" asp-action="AddPhoto" method="post" enctype="multipart/form-data">
            <div class="form-group">
                <p>
                    <label asp-for="Description"></label>
                    <textarea asp-for="Description" class="form-control"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </p>
                <p>
                    <label asp-for="States"></label>
                    <span asp-validation-for="States" class="text-danger"></span>
                    <select class="form-control" asp-for="States">
                    @{
                        foreach (var states in @ViewBag.all_states)
                        {
                            <option>@states</option>
                        }
                    }
                    </select>
                </p>
                <p>
                    <label asp-for="City"></label>
                    <input asp-for="City" class="form-control"/>
                    <span asp-validation-for="City" class="text-danger"></span>
                </p>
                <p>
                    <label asp-for="Address"></label>
                    <textarea asp-for="Address" class="form-control"></textarea>
                </p>
                <p>
                    <label asp-for="DateOfVisit"></label>
                    <input asp-for="DateOfVisit" type="date" class="form-control"/>
                    <span asp-validation-for="DateOfVisit" class="text-danger"></span>
                </p>
                <p>
                    <div class="custom-file">
                        <label asp-for="PictName" class="custom-file-label"></label>
                        <input asp-for="PictName" class="form-control" type="file" class="custom-file-input"/>
                        <span asp-validation-for="PictName" class="text-danger"></span>
                    </div>
                </p>
                <br>
                <div class="row">
                    <div class="col-md-12"><button class="btn btn-success form-control" type="submit">Create</button></div>
                </div>
            </div>
        </form>
    </div>
    <div class="col-md-6">
        <img src="~/images/camera.jpg" width="65%" height="550px" class="upload mt30">
    </div>
</div>

Views/Travel/Dashboard.cshtml
<div class="row mt30">
    <div class="col-lg-8 col-sm-12">
        <link rel="stylesheet" href="~/css/jquery-jvectormap-2.0.3.css" type="text/css" media="screen"/>

    <script src="~/js/jquery-jvectormap-2.0.3.min.js"></script>
    <script src="~/js/usa.js"></script>


<script>
    $(document).ready(function() {
        var gdpData = 
        {"AL": 0,"AK": 0,"AS": 0,"AZ": 0,"AR": 0,"CA": 0,"CO": 0,"CT": 0,"DE": 0,"DC": 0,"FM": 0,"FL": 0,"GA": 0,"GU": 0,"HI": 0,"ID": 0,"IL": 0,"IN": 0,"IA": 0,"KS": 0,"KY": 0,"LA": 0,"ME": 0,"MH": 0,"MD": 0,"MA": 0,"MI": 0,"MN": 0,"MS": 0,"MO": 0,"MT": 0,"NE": 0,"NV": 0,"NH": 0,"NJ": 0,"NM": 0,"NY": 0,"NC": 0,"ND": 0,"MP": 0,"OH": 0,"OK": 0,"OR": 0,"PW": 0,"PA": 0,"PR": 0,"RI": 0,"SC": 0,"SD": 0,"TN": 0,"TX": 0,"UT": 0,"VT": 0,"VI": 0,"VA": 0,"WA": 0,"WV": 0,"WI": 0,"WY": 0 };

        var statesAvailable = @Html.Raw(ViewBag.MyStates);

        for(var key in gdpData)
        {
            for(var states = 0; states < statesAvailable.length; states++)
            {
                if(key == statesAvailable[states].States)
                {
                    gdpData[key] += 1;
                }
            }
            console.log(key + " = " + gdpData[key]);
        }


        $('#usermap').vectorMap({
            map: 'us_aea',
            zoomOnScroll: false,
            backgroundColor: 'white',
            onRegionClick: function(e, code){
                window.open("CollectivePhotos/" + code, "_self");
            },
            series: {
                regions: [{
                    values: gdpData,
                    scale: ['#f2ebea','#dd2508'],
                    normalizeFunction: 'polynomial'
                }]
            },
        });
    });
</script>
<div id="usermap" style="width: 100%; height:400px"></div>
</div>
    <div class="col-lg-4 col-sm-12">
        @{
            foreach(var item in @ViewBag.User){
                <h3><i class="fas fa-user-circle"></i> @item.FirstName @item.LastName</h3>
                <h4>@item.Email</h4>
                <p><label>Total Uploaded: @ViewBag.Count</label></p>
                <div class="row"><br></div>
                <h4>Most Visted Places</h4>
                @foreach (var i in @ViewBag.MostVisted)
                    {
                        <h3>@i.Item2 : @i.Item1.ToString() times </h3>
                    }
            }
        }
        
    </div>
</div>
<div class="row"><br></div>
<div class="row  text-center">
    <div class="col-md-5 align-middle mt20"><hr/></div>
    <div class="col-md-2"><h3>Explored Places</h3></div>
    <div class="col-md-5 align-middle mt20"><hr/></div>
</div>
<div class="row"><br></div>
<div class="row">
@{
    foreach(var item in @ViewBag.AllUploaded){
        <div class="col-md-3">
            <div class="thumbnail thumbnailDash">
                <a href="viewUser/@item.PictureId">
                    <img src="~/images/@item.PictName" alt="Lights" class="photosize">
                </a>
                <div class="caption">
                    <p>@item.City, @item.States</p>
                    <p>@item.Address</p>
                </div>
            </div>
        </div>
    }
}

<div class="row">
    <div class="col-md-12 text-right">
        <form asp-controller="Travel" asp-action="Create" method="get">
            <button type="submit" class="btn btn-primary">Add new picture</button>
            <input type="hidden" value="Dashboard" name="Page">
        </form>
    </div>
</div>

Views/Travel/ViewPicture.cshtml
<div class="row">
    @{
            <div class="row mt30">
                <div class="col-md-9 col-12"><img src= "~/images/@ViewBag.Pic.PictName" class="enlargepic"></div>
                <div class="col-md-3 col-12 vcenter">
                <h4>Description:  @ViewBag.Pic.Description</h4>
                @if( @ViewBag.Pic.City != null){
                    <h4>@ViewBag.Pic.Address</h4>
                    <h4> @ViewBag.Pic.City,  @ViewBag.Pic.States</h4>
                }else{
                    <h4>In @ViewBag.Pic.States</h4>
                }
                <h4>@ViewBag.Pic.DateVisited.ToString("MMMM dd, yyyy")</h4>
                <br>
                <h4>Explored by <a href="/CollectivePhotos/viewUser/@ViewBag.Pic.Uploader.Userid"> @ViewBag.Pic.Uploader.FirstName  @ViewBag.Pic.Uploader.LastName</a></h4>
                </div>
            </div>
            <div class="row"><br></div>
                <div class="row  text-center">
                    <div class="col-md-5 align-middle mt20"><hr/></div>
                    <div class="col-md-2"><h3>Comments</h3></div>
                    <div class="col-md-5 align-middle mt20"><hr/></div>
                </div>
            <div class="row"><br></div>
            foreach (var comments in @ViewBag.Comment)
            {
                <div class="row comments">
                    <div class="col-md-9">
                        <h4><a href="/CollectivePhotos/viewUser/@comments.Sender.Userid">@comments.Sender.FirstName</a> @comments.CommentText</h4>
                    </div>
                    <div class="col-md-3">
                        <p>@comments.Created_At.ToString("MMM dd,yyyy hh:mm tt") <a href="delete/@comments.Commentid"> <i class="fas fa-trash-alt"></i></a></p>
                        
                    </div>
                </div>
                <div class="comments"><hr/></div>
                
            }
            <div class="row comments mt30">
                <form action ="/comment" method ="post">
                <div class="form-group">
                    <div class="col-md-10 col-12">
                        <label name="comment">Comments</label>
                        <textarea name="comment" class="form-control"></textarea>
                        <input type="hidden" name="photoID" value=@ViewBag.Pic.PictureId>
                    </div>
                    <br>
                    <div class="col-md-2 col-12">
                        <button class="btn btn-info form-control cmtbtn" type="submit">Add a comment</button>
                    </div>

                </div>
            </form>
            </div>

        }
</div>